# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  schedule:
    - cron: "0 0 * 0 0"

name: get-commit-bibs

jobs:
  get-commit-bibs:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 2
      
      # run my scripts
      - name: Get Pubmed entries
        run: |
          source("pubmed.R")
          search_pubmed("Michael Cuoco")
        shell: Rscript {0}
      - name: Get BioRxiv entries
        run: |
          source("biorxiv.R")
          search_biorxiv("Michael Cuoco")
        shell: Rscript {0}

      - name: Commit results
        run: |
          git config --global user.email "mcuoco12@gmail.com"
          git config --global user.name "mikecuoco"
          git add --all || echo "No changes to add"
          git commit -m 'Re-build publications and preprints' || echo "No changes to commit"
          git push origin || echo "No changes to commit"